export const CHANGED_NAME = 'CHANGED_NAME';
export const CHANGED_AGE = 'CHANGED_AGE';
export const CHANGED_DAY_PERIOD = 'CHANGED_DAY_PERIOD';
export const CHANGED_UPDATE_TIME = 'CHANGED_UPDATE_TIME';
export const CHANGED_TEMPERATURE_SCALE = 'CHANGED_TEMPERATURE_SCALE';
export const SET_TEMPERATURE_SCALE = 'SET_TEMPERATURE_SCALE';
