export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const LOADING = 'LOADING';
export const LATE_NAVIGATION = 'LATE_NAVIGATION';
export const RESET_LATE_NAVIGATION = 'RESET_LATE_NAVIGATION';
