export const QUERY_CHANGED = 'QUERY_CHANGED';
export const GET_WEATHER_FOR_CITIES = 'GET_WEATHER_FOR_CITIES';
export const GET_WEATHER_FOR_CITIES_SUCESS = 'GET_WEATHER_FOR_CITIES_SUCESS';
export const RESET_QUERY = 'RESET_QUERY';
export const CHANGE_CITY = 'CHANGE_CITY';
export const PRESSED_CITY = 'PRESSED_CITY';
export const SET_LOADING = 'SET_LOADING';
